name: Greet Everyone
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: test
        uses: docker://alpine
        with:
          entrypoint: ""
          args: apk add curl wget
